# -*- coding: utf-8 -*-
"""Exercicios Python - Condicionais

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rVvXv3GpFPj15hOUx5WZHQVpSqWQjXrR

## QUESTÃO 01
O que é impresso ao digitar 1+1+1 ==3?
"""

1+1+1 == 3

# AO DIGITA 1+1+1 == 3, SERÁ IMPRESSO 'TRUE'

"""# QUESTÃO 02
Considere que a variável is_ready é do tipo booleano. Qual declaração está correta e é a forma mais sucinta de testar se is_ready é verdadeiro? Complemente com a condição adequada.
"""

# if(is_ready):

is_ready = int(input('VALOR:  '))
for x in range(10):
  if (is_ready == x):
    print('ENTROU NO: ',x)
  else:
    print('ERRADO: ',x)

"""# QUESTÃO 03
A linguagem Python permite o uso de funções matemáticas. Porém, não são nativas da linguagem e ficam localizadas em módulos externos. Para se usar a função sqrt, por exemplo, é necessário usar um comando.

Faça uma pesquisa breve e responda qual o módulo externo utilizado.
"""

# USANDO O import.math E math.sqrt()

import math

n = float(input('DIGITE UM NÚMERO: '))

print("RAIZ = {}".format(math.sqrt(n)))

"""# QUESTÃO 04
Considere o trecho de comandos abaixo. Qual o número da linha que será responsável pela saída (apresentação do resultado ao usuário) desse código?

1.  texto = "computação"
2.  if len(texto) > 10:
3.      print ("texto com mais de 10 caracteres")
4.  else:
5.      print ("texto com 10 ou menos caracteres")
"""

texto = "COMPUTAÇÃO"                                    #1
if len(texto)> 10:                                      #2
  print("TEXTO COM MAIS DE 10 CARACTERES")              #3
else:                                                   #4
  print("TEXTO COM 10 OU MENOS CARACTERES")             #5   
                                                        # A LINHA 5 É RESPONSÁVEL PELA SAIDA DE DADOS, DESTE CÓDIGO!

"""#QUESTÃO 05
A legislação de trânsito do Brasil permite que apenas pessoas com no mínimo 18 anos possam habilitar-se para dirigir.
Considere que exista uma variável idade e você deverá testar se o usuário pode dirigir ou não e, em seguida, exibir uma mensagem correspondente à sua situação. Todas as opções abaixo dão o resultado correto, porém, qual delas utiliza melhor o recurso do if..else?

I: if (idade < 18): 
      print ("Não pode tirar carteira de habilitação")
   if (idade >= 18):
      print ("Pode tirar a carteira de habilitação")
      
II: if (idade < 18): 
       print ("Não pode tirar carteira de habilitação")
    else: 
       print ("Pode tirar a carteira de habilitação")
       
III: if (idade < 18): 
          print (" Não pode tirar carteira de habilitação")
     else: 
         if (idade >= 18): 
               print ("Pode tirar a carteira de habilitação")

IV: if (idade < 18): 
       print ("Não pode tirar carteira de habilitação")
    else: 
      if (idade == 18): 
          print ("Pode tirar a carteira de habilitação")
      else: 
           if (idade > 18): 
               print ("Pode tirar a carteira de habilitação")
               
"""

idade = int(input("DIGITE A SUA IDADE: "))

if (idade < 18):
   print ("NÃO PODE TIRAR CARTEIRA DE HABILITAÇÃO")
else: 
  print ("PODE TIRAR A CARTEIRA DE HABILITAÇÃO")

# RESPOSTA CORRETA: II

"""#QUESTÃO 06
Considere a=0, b = 2 e c = 1. O que será impresso pelos comandos abaixo? (Primeiro ajuste corretamente a indentação.)

if (a > 0):
    if (b > 0):
        print ("Tudo ok para decolagem!")
    else:
        print ("Tanque principal vazio; voando com combustível reserva!")
else:
    if (c > 0):
        print ("Foguete não tem piloto, mas há outros foguetes disponíveis!")
"""

a=0
b=2
c=1

if (a > 0):
    if (b > 0):
        print ("Tudo ok para decolagem!")
    else:
        print ("Tanque principal vazio; voando com combustível reserva!")
else:
    if (c > 0):
        print ("Foguete não tem piloto, mas há outros foguetes disponíveis!")

# SERÁ IMPRESSO "FOGUETE NÃO TEM PILOTO, MAS HÁ OUTROS FOGUETES DISPONÍVEIS!"

"""#QUESTÃO 07
Escreva um programa que calcula as raízes de uma equação do segundo grau. O programa deve receber os parâmetros a, b, e c da equação ax2+bx+c , respectivamente, e imprimir o resultado na saída da seguinte maneira:

Quando não houver raízes reais imprima:

esta equação não possui raízes reais

Quando houver apenas uma raiz (ou seja, uma raiz com multiplicidade 2) imprima:

a raiz desta equação é X

ou

a raiz dupla desta equação é X

onde X é o valor da raiz dupla

Quando houver duas raízes reais imprima:

as raízes da equação são X e Y

onde X e Y são os valores das raízes.

Além disso, no caso de existirem 2 raízes reais distintas, elas devem ser impressas em ordem crescente. Exemplos:

as raízes da equação são 1.0 e 2.0

as raízes da equação são -2.0 e 0.0
"""

from math import sqrt
print("DIGITE OS PARÂMETROS A, B, e C DA EQUAÇÃO(ax²+bx+c)")

p_a = float(input("DIGITE O PARÂMETRO A: "))
p_b = float(input("DIGITE O PARÂMETRO B: "))
p_c = float(input("DIGITE O PARÂMETRO C: "))

delta = ((p_b ** 2) - (4 * p_a * p_c))

if (delta < 0):
    print("ESSA EQUAÇÃO NÃO POSSUI RAÍZES REAIS")
elif (delta > 0):
# PARA IMPRIMIR EM ORDEM CRESCENTE
    x1 = ((p_b * (-1)) + sqrt(delta)) / (2 * p_a)
    x2 = ((p_b * (-1)) - sqrt(delta)) / (2 * p_a)
    if (x1 > x2):
        aux = x1
        x1 = x2
        x2 = aux
    print("AS RAÍZES DA EQUAÇÃO SÃO {} E {}".format(x1, x2))
else:
    x1 = ((p_b * (-1)) + sqrt(delta)) / (2 * p_a)
    print("A RAIZ DESTA EQUAÇÃO É {}".format(x1))

"""#QUESTÃO 08
Receba 3 números inteiros na entrada e imprima:

Crescente

Se eles forem dados em ordem crescente. Caso contrário, imprima

não está em ordem crescente
"""

# NÃO FIZ USANDO O IF,ELIF E ELSE, POIS ESTAVA TESTANDO A LISTA, GOSTEI DE QUANDO ESTUDEI E VI A SUA PRATICIDADE, ESPERO QUE ISSO NÃO INCOMODE
# DEIXEI FLOAT, AO INVÉS DE INT, POIS ACHO MELHOR QUANDO O ASSUNTO É NÚMERO. 
# COM INT SERIA 'nX = int(input("DIGITE O XºNUMERO: "))'
n1 = float(input("DIGITE O 1ºNÚMERO: "))
n2 = float(input("DIGITE O 2ºNÚMERO: ")) 
n3 = float(input("DIGITE O 3ºNÚMERO: "))

Lsta=[n1,n2,n3]
print(sorted(Lsta))

"""#QUESTÃO 09
Receba 4 números na entrada, um de cada vez. Os dois primeiros devem corresponder, respectivamente, às coordenadas x e y de um ponto em um plano cartesiano. Os dois últimos devem corresponder, respectivamente, às coordenadas x e y de um outro ponto no mesmo plano.

Calcule a distância entre os dois pontos. Se a distância for maior ou igual a 10, imprima

longe

Caso contrário, quando a distância for menor que 10, imprima

perto

Dica: lembre-se que a fórmula da distância para dois pontos num plano cartesiano é a seguinte: d(x,y)=√(x1−x2)²+(y1−y2)² 
"""

import math

x1 = int(input("DIGITE O VALOR DE X1: "))
y1 = int(input("DIGITE O VALOR DE Y1: "))
x2 = int(input("DIGITE O VALOR DE X2: "))
y2 = int(input("DIGITE O VALOR DE Y2: "))

# X #

if x1 < 0 and x2 >= 0:  
    x3 = (x1*-1) + x2
elif x1 >= 0 and x2 < 0:
    x3 = x1 + (x2 * -1)
elif x1 < 0 and x2 < 0:
    if x1 > x2:
        x3 = x1 - x2
    else:
        x3 = x2 - x1
elif x1 >= 0 and x2 >= 0:
    if x1 >= x2:
        x3 = x1 - x2
    else:
        x3 = x2 - x1
        
# Y #

if y1 < 0 and y2 >= 0:  
    y3 = (y1*-1) + y2
elif y1 >= 0 and y2 < 0:
    y3 = y1 + (y2 * -1)
elif y1 < 0 and y2 < 0:
    if y1 > y2:
        y3 = y1 - y2
    else:
        y3 = y2 - y1
elif y1 >= 0 and y2 >= 0:
    if y1 >= y2:
        y3 = y1 - y2    
    else:
        y3 = y2 - y1

resultado = math.sqrt(x3**2 + y3**2) 

if resultado >= 10:
    print("LONGE")
else:
    print("PERTO")

"""#QUESTÃO 10
Você foi contratado(a) para elaborar um script em Python para um caixa eletrônico. O programa deverá perguntar ao usuário a valor do saque e depois informar quantas notas de cada valor serão fornecidas. As notas disponíveis serão as de 1, 5, 10, 50 e 100 reais. O valor mínimo é de 10 reais e o máximo de 600 reais. O programa não deve se preocupar com a quantidade de notas existentes na máquina.

Exemplo 1: Para sacar a quantia de 256 reais, o programa fornece duas notas de 100, uma nota de 50, uma nota de 5 e uma nota de 1;
Exemplo 2: Para sacar a quantia de 399 reais, o programa fornece três notas de 100, uma nota de 50, quatro notas de 10, uma nota de 5 e quatro notas de 1.

"""

print("VALOR MÍNIMO E MÁXIMO DO SAQUE [10-600].")
saque = int(input("VALOR DO SAQUE: R$ "))

while (saque<10) or (saque>600):
  print("VALOR FORA DOS LIMITES!")
  saque = int(input("DIGITE NOVAMENTE: R$ "))

if (saque>=10) and (saque<=600):
  resto1 = saque % 100
  resto2 = resto1 % 50
  resto3 = resto2 % 10
  resto4 = resto3 % 5
  nota100,nota50,nota10,nota5,nota1 = (saque//100,resto1//50,resto2//10,resto3//5,resto4//1)

print("\nRETORNO:")
print("R$100,00:",nota100)
print("R$50,00: ",nota50)
print("R$10,00: ",nota10)
print("R$5,00:  ",nota5)
print("R$1,00:  ",nota1)

"""#QUESTÃO 11
O Hipermercado Tabajara está com uma promoção de carnes que é imperdível. Confira:

                      Até 5 Kg           Acima de 5 Kg
File Duplo      R$ 4,90 por Kg         R$ 5,80 por Kg
Alcatra         R$ 5,90 por Kg          R$ 6,80 por Kg
Picanha         R$ 6,90 por Kg          R$ 7,80 por Kg

Para atender a todos os clientes, cada cliente poderá levar apenas um dos tipos de carne da promoção, porém não há limites para a quantidade de carne por cliente. 
Se a compra for feita no cartão Tabajara o cliente receberá ainda um desconto de 5% sobre o total da compra. 
Escreva um programa que peça o tipo e a quantidade de carne comprada pelo usuário e gere um cupom fiscal, contendo as informações da compra: tipo e quantidade de carne, preço total, tipo de pagamento, valor do desconto e valor a pagar.
"""

print("1- FILE DUPLO\n2- ALCATRA\n3- PICANHA\n\n")
tipo = int(input("DIGITE UMA DAS OPÇÕES ACIMA: "))
quantidade = int(input("DIGITE A QUANTIDADE (KG): "))
resposta = int(input("A COMPRA SERÁ REALIZADA COM CARTÃO TABAJARA? 1-SIM - 2-NAO: "))

if tipo == 1:
    nome = "FILE DUPLO"
    if quantidade <= 5:
        preco = quantidade * 4.90
    else:
        preco = quantidade * 5.80
        
if tipo == 2:
    nome = "ALCATRA"
    if quantidade <= 5:
        preco = quantidade * 5.90
    else:
        preco = quantidade * 6.80

if tipo == 3:
    nome = "PICANHA"
    if quantidade <= 5:
        preco = quantidade * 6.90
    else:
        preco = quantidade * 7.80

if resposta == 1:
    r = "SIM"

    desconto = ((preco * 5) /100)
    total = preco - desconto
else:
    r = "NAO"
    total = preco
    
print("\n***************************CUPOM FISCAL**************************************")
print("* CARNE.......................................................... %s " %nome)
print("* QUANTIDADE..................................................... %d KG " %quantidade)
print("* PREÇO.......................................................... %2.f R$ " %preco)
print("* CARTÃO TABAJARA................................................ %s " %r)
print("* TOTAL COM DESCONTO............................................. %2.f R$ " %total)
print("******************************************************************************")